// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LessonsListModuleScssNamespace {
    export interface ILessonsListModuleScss {
        lessonsList: string;
        listInner: string;
    }
}

declare const LessonsListModuleScssModule: LessonsListModuleScssNamespace.ILessonsListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LessonsListModuleScssNamespace.ILessonsListModuleScss;
};

export = LessonsListModuleScssModule;
