// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InstrumentsTableModuleScssNamespace {
    export interface IInstrumentsTableModuleScss {
        instrument: string;
        instrumentsList: string;
    }
}

declare const InstrumentsTableModuleScssModule: InstrumentsTableModuleScssNamespace.IInstrumentsTableModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InstrumentsTableModuleScssNamespace.IInstrumentsTableModuleScss;
};

export = InstrumentsTableModuleScssModule;
