// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LessonsItemModuleScssNamespace {
    export interface ILessonsItemModuleScss {
        itemCover: string;
        itemDescription: string;
        itemLessonsNumber: string;
        listItem: string;
        listItemInner: string;
    }
}

declare const LessonsItemModuleScssModule: LessonsItemModuleScssNamespace.ILessonsItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LessonsItemModuleScssNamespace.ILessonsItemModuleScss;
};

export = LessonsItemModuleScssModule;
