// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CoursesItemModuleScssNamespace {
    export interface ICoursesItemModuleScss {
        itemCover: string;
        itemDescription: string;
        itemLessonsNumber: string;
        listItem: string;
        listItemInner: string;
    }
}

declare const CoursesItemModuleScssModule: CoursesItemModuleScssNamespace.ICoursesItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CoursesItemModuleScssNamespace.ICoursesItemModuleScss;
};

export = CoursesItemModuleScssModule;
