// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContentBlockModuleScssNamespace {
    export interface IContentBlockModuleScss {
        active: string;
        blockBanner: string;
        contentBlock: string;
        contentBlockTest: string;
    }
}

declare const ContentBlockModuleScssModule: ContentBlockModuleScssNamespace.IContentBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ContentBlockModuleScssNamespace.IContentBlockModuleScss;
};

export = ContentBlockModuleScssModule;
