// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CoursesListModuleScssNamespace {
    export interface ICoursesListModuleScss {
        coursesList: string;
        listInner: string;
    }
}

declare const CoursesListModuleScssModule: CoursesListModuleScssNamespace.ICoursesListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CoursesListModuleScssNamespace.ICoursesListModuleScss;
};

export = CoursesListModuleScssModule;
