// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FooterModuleScssNamespace {
    export interface IFooterModuleScss {
        footer: string;
        footerInner: string;
        footerLogo: string;
    }
}

declare const FooterModuleScssModule: FooterModuleScssNamespace.IFooterModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FooterModuleScssNamespace.IFooterModuleScss;
};

export = FooterModuleScssModule;
