// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppScssNamespace {
    export interface IAppScss {
        app: string;
        button: string;
        buttonActive: string;
        chart: string;
        leftBlock: string;
        myChart: string;
        online: string;
        onlineTrue: string;
        rightBlock: string;
        toolsUp: string;
    }
}

declare const AppScssModule: AppScssNamespace.IAppScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AppScssNamespace.IAppScss;
};

export = AppScssModule;
