// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageHeroModuleScssNamespace {
    export interface IPageHeroModuleScss {
        itemLessonsNumber: string;
        pageHero: string;
        pageHeroInner: string;
        pageHeroMain: string;
        pageHeroPic: string;
    }
}

declare const PageHeroModuleScssModule: PageHeroModuleScssNamespace.IPageHeroModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PageHeroModuleScssNamespace.IPageHeroModuleScss;
};

export = PageHeroModuleScssModule;
