// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RadioButtonTestModuleScssNamespace {
    export interface IRadioButtonTestModuleScss {
        textStatus: string;
        textStatusFalse: string;
        textStatusTrue: string;
    }
}

declare const RadioButtonTestModuleScssModule: RadioButtonTestModuleScssNamespace.IRadioButtonTestModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RadioButtonTestModuleScssNamespace.IRadioButtonTestModuleScss;
};

export = RadioButtonTestModuleScssModule;
